[package]
name = "image-resizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.9"
libwebp-sys = "0.9.5"
magick_rust = "0.20.0"
mozjpeg = "0.10.6"
oxipng = "9.0.0"
