[package]
name = "respicta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
axum = { version = "0.7.4", features = ["multipart"] }
clap = { version = "4.5.3", features = ["derive"] }
image = "0.25.0"
libwebp-sys = "0.9.5"
magick_rust = "0.20.0"
oxipng = "9.0.0"
tempfile = "3.10.1"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
axum-test = "14.4.0"
