name: Release to crate.io

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: publish
          secrets: |
            CARGO_REGISTRY_TOKEN=${{ secrets.CARGO_REGISTRY_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
