name: Release to crate.io

on:
  push:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: publish
